### PR TITLE
removed line about risk assesments

### PR DESCRIPTION
**Pull request by grbd**
Removed the line about the risk assesments, not sure where that came from
also I'm not on the Documentation team btw

### CODE REVIEW

**Comment by conorriches** [comment]
How come you'd like this to be totally removed? If it is incorrect it could be amended

**Comment by grbd** [comment]
It seems to imply I'll be writing lots of risk assesments for some reason??
Perhaps the wires got a bit crossed, I updated the risk assesment for one tool which is the wood lathe, then tried to get it approved. I think it's currently waiting on board approval

Practically speaking the only thing left I think to get the wood lathe working is to just get the table and it all re-fastend down after it's move.

**Comment by grbd** [comment]
okay I've now updated the points associated with the CNC / wood lathe

**Comment by conorriches** [comment]
This matches my memory of the meeting so I'm happy to approve this change

**Comment by conorriches** [comment]
May be worth checking with Bunny Girl too as she wrote the minutes

**Comment by grbd** [comment]
if you read the comments above there was some suggestion I'd be writing lots of risk assesments for some reason?

**Pull request merged**
